// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ox21FjoT1yWiCxKcAHMHlOVL5pnZW5I',
    appId: '1:728288465201:web:707c3cce0ed8e16f982010',
    messagingSenderId: '728288465201',
    projectId: 'prjctjestha',
    authDomain: 'prjctjestha.firebaseapp.com',
    storageBucket: 'prjctjestha.appspot.com',
    measurementId: 'G-PPC82ZMRD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqm21HS8JlHb--73mLL8ZLnkFjWR4Iblw',
    appId: '1:728288465201:android:5a2ac9f863477ccf982010',
    messagingSenderId: '728288465201',
    projectId: 'prjctjestha',
    storageBucket: 'prjctjestha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbyMSVvOr5WCbjqa5Iuk1LMcjHPvF0skE',
    appId: '1:728288465201:ios:b4b79d9082764ae3982010',
    messagingSenderId: '728288465201',
    projectId: 'prjctjestha',
    storageBucket: 'prjctjestha.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbyMSVvOr5WCbjqa5Iuk1LMcjHPvF0skE',
    appId: '1:728288465201:ios:7382c8e0f26b8752982010',
    messagingSenderId: '728288465201',
    projectId: 'prjctjestha',
    storageBucket: 'prjctjestha.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
